require 'cocoapods'
require 'octokit'
require 'pry'

class Pod::Specification
  class << self
    def github_client
      #puts 'github token: ' + ENV['GITHUB_TOKEN']
      @client ||= Octokit::Client.new(:access_token => ENV['GITHUB_TOKEN'])

      #check rate limit
      rateLimitRemaining = @client.rate_limit.remaining
      puts 'rate limit remaining: ' + rateLimitRemaining.to_s
      sleepAmount = 1
      while rateLimitRemaining < 1
        sleep sleepAmount
        sleepAmount += 2
        rateLimitRemaining = self.class.github_client.rate_limit.remaining
      end
      return @client
    end
  end

  def github_rate_limit_remaning
    self.class.github_client.rate_limit.remaining
  end

  def git_repo
    source[:git]
  end

  def github?
    git_repo && git_repo.start_with?('https://github.com')
  end

  def github_repo_name
    match_data = git_repo.match("https://github.com/(.+?)/(.+?).git")
    "#{match_data[1]}/#{match_data[2]}"
  end

  def github_repo
    @repo ||= self.class.github_client.repo(github_repo_name)
  end
end

specs = Pod::SourcesManager.all_sets.map(&:specification)
puts 'Number of specs: ' specs.count
#specs = specs.first(5) # For testing

github_specs = specs.select do |spec|
  puts "Checking #{spec.name}"

  begin
    spec.github? && !!spec.github_repo
  rescue Octokit::NotFound
    false
  end
end
github_specs = github_specs.sort_by { |spec| - spec.github_repo.stargazers_count }


File.open("cocoapods_rank.md", "w+") do |f|
  f.puts "# CocoaPods Rank"
  f.puts "\n"
  f.puts "Sorted by stargazers count of GitHub repo (as of #{Time.now})"
  f.puts "\n"
  f.puts "[Source code](https://github.com/mrkd/cocoapods_rank)"
  f.puts "\n"

  github_specs.each do |spec|
    puts "#{spec.name}: #{spec.github_repo.stargazers_count}"
    f.puts "* #{spec.github_repo.stargazers_count} [#{spec.name}](#{spec.homepage})"
  end

  f.puts "\n"
  f.puts "Generated by [@mrkdsys](https://github.com/mrkd/)"
  f.puts "Forked from [@luvtechno](https://github.com/luvtechno/)"
end

# stargazers_count
# forks_count

# binding.pry
